---

- name: Create wikijs user
  user:
    name: "{{ wikijs_user }}"
    group: "{{ wikijs_group }}"
    create_home: yes

- name: Create wikijs directory
  file:
    path: "{{ wikijs_dir }}"
    state: directory
    owner: "{{ wikijs_user }}"

- name: Download wiki-js.tar.gz
  get_url:
    url: "{{ wikijs_url }}"
    dest: "{{ wikijs_dir }}"
    owner: "{{ wikijs_user }}"

- name: Extract wiki-js.tar.gz
  unarchive:
    src: "{{ wikijs_dir }}/wiki-js.tar.gz"
    dest: "{{ wikijs_dir }}"
    remote_src: true

- name: Copy config.yml file
  template:
    src: "files/config.yml"
    dest: "{{ wikijs_dir }}/config.yml"
    owner: "{{ wikijs_user }}"
    group: "{{ wikijs_group }}"
    mode: '0644'

- name: Copy wikijs.service file
  template:
    src: "files/wikijs.service"
    dest: "/etc/systemd/system/wikijs.service"
    owner: root
    group: root
    mode: '0644'

- name: Install nodejs
  apt:
    name: nodejs

- name: Start wikijs.service + reload systemd
  service:
    name: wikijs
    state: started
    enabled: yes
    daemon_reload: true